apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
  - name: karpenter-crd
    repo: oci://public.ecr.aws/karpenter
    version: 1.3.2
    releaseName: karpenter-crd
    namespace: kube-system
    includeCRDs: true
