apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: karpenter

resources:
  - https://raw.githubusercontent.com/aws/karpenter-provider-aws/v1.0.0/config/crds/karpenter.sh_provisioners.yaml
  - https://raw.githubusercontent.com/aws/karpenter-provider-aws/v1.0.0/config/crds/karpenter.sh_nodepools.yaml
  - https://raw.githubusercontent.com/aws/karpenter-provider-aws/v1.0.0/config/crds/karpenter.k8s.aws_awsnodetemplates.yaml

helmCharts:
  - name: karpenter
    repo: https://charts.karpenter.sh
    version: 1.1.0
    releaseName: karpenter
    namespace: karpenter
    valuesFile: values.yaml
