apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow

helmCharts:
  - name: airflow
    repo: https://airflow.apache.org
    version: 1.14.0
    releaseName: airflow
    namespace: airflow
    valuesFile: values.yaml

resources:
  - volume-setup.yaml
