apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: karpenter

helmCharts:
  - name: karpenter
    repo: oci://public.ecr.aws/karpenter
    version: 1.3.2
    releaseName: karpenter
    namespace: karpenter
    valuesFile: override-values.yml

resources:
  - nodeclass.yaml
  - nodepool.yaml
