apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
  - name: karpenter
    repo: oci://public.ecr.aws/karpenter
    version: 1.3.2
    releaseName: karpenter
    namespace: kube-system
    valuesFile: override-values.yml
